### ISSUE TITLE
Skills Levelling - MC 1.19.4 - SMMO 0.1.9

### ISSUE THREAD

**Issue by Extector** [nickrobson/skillmmo#1]
The blocks and even the items that leveling up skills provides, doesn't work.
Some of the blocks:
- Bed
- Diamond Sword
- Ladders
- Labs
- Furnance
And others. Do I need to put every item/block that isn't working as expected to craft?
(What is interesting is that I'm able to create a bucket).
I tried to reload after leveling up and reinstall the mod but it did nothing.

**Comment by nickrobson** [comment]
Thanks for reporting this! I'll have a go at reproducing this and I'll let you know.
Could you please share any other mods you've got installed and whether you've made any changes to the mod config?

**Comment by nickrobson** [comment]
I've just tested some stuff. With only Fabric API and Cloth Config installed, I created a new single-player world, levelled up to Survival 1 and Building 3, and was able to craft beds and ladders. I'm going to guess that our setups are slightly different, so if you could just let me know what version of Fabric loader and API etc. you're using, I can test it with a similar setup to what you've got.

(BTW (related but unrelated), I've just added some issue templates to this repo to prompt for some extra info like this for future issues. If you'd like, you're welcome to re-create this issue with the new bug report template, but no worries if you just want to keep this one.)

**Comment by Extector** [comment]
I'll create a new one with everything that I'm currently using! Thanks!
