### ISSUE TITLE
Nether Causes a Skill Level Reset

### ISSUE THREAD

**Issue by MaKuronie** [nickrobson/skillmmo#4]
**Describe the bug**
Upon entering or exiting the nether dimension via portal or waystone the player's skill levels get reset to zero until a stat is leveled up to where it will return to its original value.

**Minecraft and Fabric version**
Minecraft 1.19.4
Fabric Loader 0.14.21
Fabric API  0.84.0

**Config changes**
None

**Other mods installed**
https://drive.google.com/drive/folders/1NGLIk4YYQr-TcqxpgnUOzcQsYRmWvqsa?usp=sharing

**To reproduce**
1. Create a new world
2. Level up
3. Acquire X levels any stat
4. Create a Nether Portal
5. Enter the Nether
6. See that your stats are back to 0
7. Level up and add a point to a stat
8. See your stats are back to normal
9. Leave Nether
10. See that your stats are back to 0 again

**Expected behavior**
The levels will continue to be the same upon both entering and exiting the nether

**Screenshots**
![2023-07-17_03 34 54](https://github.com/nickrobson/skillmmo/assets/105084053/c4e668b6-0f4d-4b1d-8f9c-da996d583252)
![2023-07-17_03 41 15](https://github.com/nickrobson/skillmmo/assets/105084053/0ee14714-6bf5-4215-b8ad-02984aae6735)

**Comment by nickrobson** [comment]
Thanks for reporting this @MaKuronie !
It turns out to be a simple fix, I'll submit it to Modrinth + CurseForge now (so hopefully it'll be available there tomorrow or the day after).
If you don't want to wait, I've just pushed the code with the fix and you're welcome to build it yourself.

**Comment by nickrobson** [comment]
File links:
* Modrinth: https://modrinth.com/mod/skillmmo/version/WrsD7PnF
* CurseForge: https://curseforge.com/minecraft/mc-mods/skillmmo/files/4659587
