### ISSUE TITLE
Support for Minecraft 1.20.1

### ISSUE THREAD

**Issue by MaKuronie** [nickrobson/skillmmo#5]
**Is your feature request related to a problem? Please describe.**
As of now the mod is only available for Mincraft Version 1.19.4 and it would be cool if it was updated to 1.20.1

**Describe the solution you'd like**
A version of the mod that is compatible with 1.20.1

**Describe alternatives you've considered**
A sing version that can run on versions 1.19-1.20.1

**Additional context**
None

**Comment by nickrobson** [comment]
Hey there! 👋 
Sorry for not releasing an updated version yet – it's been on my to-do list but I've just been a bit busy with a few IRL commitments.
I'll see if I can release a 1.20 update today :)

**Comment by nickrobson** [comment]
Released on Modrinth & CurseForge:
* Modrinth: https://modrinth.com/mod/skillmmo/version/0.1.11
* CurseForge: https://curseforge.com/minecraft/mc-mods/skillmmo/files/4660052 (pending approval)
