### ISSUE TITLE
Config not appearing

### ISSUE THREAD

**Issue by EtreInsurgent** [nickrobson/skillmmo#8]
The Config does not appear

1.20.1, fabric api 0.91.0

![Screenshot 2024-01-04 235722](https://github.com/nickrobson/skillmmo/assets/135174506/dbf3981c-1ff8-41e3-a7f3-f1c50f2ca53c)

**Comment by nickrobson** [comment]
Hi @EtreInsurgent , sorry for the late reply.

The screenshot you uploaded looks like a directory listing of the JAR file itself, but the config file should generate in the "config" folder inside your game instance, next to the "mods" folder where you have the JAR file.

I'll close this issue but if you still have issues, let me know and I'll re-open it.
